// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOlGJlhwgqgrdtqXDJP6BUPtWmHIhLdfY',
    appId: '1:139692644441:web:f34dcdb77eaefc6bed7948',
    messagingSenderId: '139692644441',
    projectId: 'learnapp-57da8',
    authDomain: 'learnapp-57da8.firebaseapp.com',
    storageBucket: 'learnapp-57da8.appspot.com',
    measurementId: 'G-9Z1N8X5V12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl3SjdWHHRNZ0DFEwr2dSjct1jKBUyPvY',
    appId: '1:139692644441:android:a11f683fcd00b500ed7948',
    messagingSenderId: '139692644441',
    projectId: 'learnapp-57da8',
    storageBucket: 'learnapp-57da8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2EQghEAbGAhR6Sh-U0bOkG2AurU2vpS0',
    appId: '1:139692644441:ios:dff294a49222e5a3ed7948',
    messagingSenderId: '139692644441',
    projectId: 'learnapp-57da8',
    storageBucket: 'learnapp-57da8.appspot.com',
    iosClientId: '139692644441-3s13paup76hn929p8lhtba08vm5lu9c1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eldaheeh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2EQghEAbGAhR6Sh-U0bOkG2AurU2vpS0',
    appId: '1:139692644441:ios:94f5f14a3ea17b2ded7948',
    messagingSenderId: '139692644441',
    projectId: 'learnapp-57da8',
    storageBucket: 'learnapp-57da8.appspot.com',
    iosClientId: '139692644441-t35l760o5qn5up63mvn272paueap2iin.apps.googleusercontent.com',
    iosBundleId: 'com.example.eldaheeh.RunnerTests',
  );
}
